### ISSUE TITLE
Problem Golem.de

### ISSUE THREAD

**Issue by radlerandi** [mbirth/ttrss_plugin-af_feedmod#32]
Ich bekomme es nicht mehr hin, dass mir die Volltexte in ttrss gespeichert werden. 
Egal welche Einstellung ich nehme, kein Text mehr seit dem Umzug aufs eigene NAS und damit verbundenen Update auf v1.11.
Bei v1.7.9 funktionierte das noch.

auch in Kombinationen funktioniert weder 
"rss.feedsportal.com" noch "golem0Bde0C" 
für "xpath"
"article" or "div[@class='g g4 g-ie6']"}
et cetera...
ratlos.

**Comment by nbartels** [comment]
Also ich nutze ```http://rss.golem.de/rss.php?feed=ATOM1.0``` als Quelle für Golem und sehe da im link-tag nur URLs die mit ```http://www.golem.de``` beginnen. Darum habe ich auch statt ```golem0Bde0C``` einfach ```golem.de``` eingetragen (sonstige Konfiguration wie im Beispiel) und erhalte den gesamten Text. Optimal ist der zwar noch nicht, weil bspw die Bildergalerien "defekt" sind, aber insgesamt passt das schon. Und zumindest ist der Text vollständig :smile:

**Comment by radlerandi** [comment]
hat sich inzwischern erledigt. mittlerweile hab ich auch multi pages. Auch ohne Bildergalerien, die klappen nicht.
```
   "golem.de": {
        "type": "xpath",
        "xpath": "article",
        "multipage": {
            "xpath": "ol/li/a[contains(@id, 'atoc_')]",
            "append": true
        },
        "reformat": [
            {
                "type": "replace",
                "search": "-rss.html",
                "replace": ".html"
            }
        ],
        "cleanup": [
            "a[@class='golem-gallery2-nojs']",
            "ol[@id='list-jtoc']",
            "table[@id='table-jtoc']",
            "div[@class='htmlinline']",
            "div[@class='iqadcenter']",
            "div[@id='iqadtile4']"
        ]
    }
